version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: downonly
      MYSQL_USER: frontend
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
      - ./dev/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"