import '@unocss/reset/sanitize/sanitize.css'
import '@unocss/reset/sanitize/assets.css'
import './uno.css'
import './globals.css'
import localFont from 'next/font/local'
import { Montserrat } from 'next/font/google'

const fontDisplay = localFont({
	src: './jegelskerdig.woff2',
	variable: '--font-display',
})
const fontBody = Montserrat({ subsets: ['latin'], variable: '--font-body' })

export const metadata = {
	title: 'Downonly',
	description: 'Generated by genuine intelligence',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang="en"
			className={`${fontDisplay.variable} ${fontBody.variable} ${fontBody.className} bg-white dark:bg-black text-black dark:text-white`}
		>
			<body>{children}</body>
		</html>
	)
}
